version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: traffic
      POSTGRES_PASSWORD: traffic
      POSTGRES_DB: trafficdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ../backend
    environment:
      DATABASE_URL: postgresql://traffic:traffic@db:5432/trafficdb
    depends_on:
      - db
    ports:
      - "8000:8000"

  simulator:
    build: ../simulator
    environment:
      DB_URL: postgresql://traffic:traffic@db:5432/trafficdb
    depends_on:
      - db

volumes:
  db_data: